[Overview] 🐛🌐 Fix AU police motorbike training
LSS-Manager/LSSM-V.4 pull request #1076
Opened 2021-12-08 20:20 UTC by Gooochy

2021-12-08 21:04 UTC, Suchty112 requested changes

2021-12-08 21:04 UTC, Suchty112 commented on src/i18n/en_AU.ts
> +                caption: 'Motor Officer',
this is wrong here, the way it was before is right. 
The caption that appears in the school and in the course window of the alliance must be placed here.
https://cdn.discordapp.com/attachments/544869019673559060/918244105979588698/unknown.png

2021-12-08 21:04 UTC, Suchty112 commented on src/i18n/en_AU.ts
> +                    'Motor Officer': {
this is also wrong, here it must be exactly the same as in the other picture or in this picture.
https://cdn.discordapp.com/attachments/544869019673559060/918244105778253914/unknown.png

2021-12-08 21:04 UTC, Suchty112 commented on src/i18n/en_AU.ts
> +                staffList: 'Motor Officer',
this should be exceptionally correct

2021-12-08 21:11 UTC, Suchty112 commented
please wait with any changes, i will do a debugbuild

2021-12-08 21:45 UTC, Suchty112 commented
We are leaving this PR in the draft until Jan looks over it. the problem with the motorbike is that it has 2 different names for the training.
Police Motorcycle at the school/in the class overview in the school/association overview or in the assignment window and Motor Officer when it has been trained.

2021-12-08 21:53 UTC, JRH-1997 commented
That's the same in NL: 
https://github.com/LSS-Manager/LSSM-V.4/blob/f8048f47e25e14ef07425b6126f583f3544687c0/src/i18n/nl_NL.ts#L1669

stafflist when it's trained, the other one in the school or when its still in training

2021-12-08 21:54 UTC, Gooochy commented
Yeah the reason I did it is in the add a vehicle tab it says motor officer

2021-12-09 14:16 UTC, Suchty112 approved these changes

2021-12-09 14:23 UTC, jxn-30 approved these changes

2021-12-09 14:36 UTC, merged