Add swedish translation for police_horse
LSS-Manager/LSSM-V.4 pull request #1168
Opened 2022-01-16 01:43 UTC by itayo

2022-01-16 11:23 UTC, Cr4zyc4k3 submitted a review, later dismissed

2022-01-16 11:26 UTC, Cr4zyc4k3 commented
Looks good for me. This modules also need translations :see_no_evil: 
- creditsextension
- dailyCreditsSummary
- extendedCallWindow
- extendedMap
- heatmap
- hotkeys
- messageTemplates
- redesign
- statusCounter

https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/creditsextension
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/dailyCreditsSummary/
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/extendedCallWindow/
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/extendedMap/
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/heatmap/
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/hotkeys/
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/messageTemplates
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/redesign/
https://github.com/LSS-Manager/LSSM-V.4/tree/dev/src/modules/statusCounter/

2022-01-16 12:39 UTC, itayo commented
> * creditsextension
> * dailyCreditsSummary
> * extendedCallWindow
> * extendedMap
> * heatmap
> * hotkeys
> * messageTemplates
> * redesign
> * statusCounter

Il take alook at them

2022-01-16 12:50 UTC, Cr4zyc4k3 commented
Thanks in advance. Don't feel liable to do all translations.It was just a quick idea.
You can add them in this MR.

2022-01-16 12:57 UTC, itayo commented
[ ] creditsextension
[ ] dailyCreditsSummary
[ ] extendedCallWindow
[ ] extendedMap
[ ] heatmap
[ ] hotkeys
[ ] messageTemplates
[ ] redesign
[ ] statusCounter

2022-01-16 13:15 UTC, jxn-30 commented
> As im guessing you guys have to verify langauge its better i do 1 MR per module imho
It is also ok to have everything in one MR, which would also be a little less work. So do it the way, you're more comfortable with.
Also, we're not checking language, as we don't speek most of the languages ^^

2022-01-16 13:16 UTC, jxn-30 requested changes

2022-01-16 13:16 UTC, jxn-30 commented on src/modules/creditsextension/i18n/sv_SE.root.json
> +sInNavbar": {
there accidentally is a `2` within the text ;)

2022-01-17 09:41 UTC, jxn-30 approved these changes

2022-01-17 09:43 UTC, merged