🔀🔖 4.5.5
LSS-Manager/LSSM-V.4 pull request #1313
Opened 2022-03-14 11:26 UTC by jxn-30

* 🐛 [ecw/eh] fix n not triggering vehicle loading
* 🐛 [redesign] fix bug when clicking same-site link
* 🚸 [telemetry] improve browser-support popup
* ⬆️ upgraded FontAwesome to 6.1.0
    * including [free Humanitarian Icons](https://fontawesome.com/icons/categories/humanitarian) and mostly free [Disaster + Crisis Icons](https://fontawesome.com/icons/categories/disaster) that could be helpful for customizable Icons within LSSM
    * [Full Changelog](https://fontawesome.com/docs/changelog/)
* ✨ [ecl/sm] new sorting methods: distance_dispatch & distance_station
* ✨ [em] open markers in new window/tab
* ✨ [redesign/bewerbungen] add credits of users
* ✨ [redesign/vehicle] allow disabling discharge confirmation
* ✨🇫🇷👮🚓 support new Content Pack 🚓👮🇫🇷✨

2022-03-15 15:53 UTC, deoxis9001 requested changes
`Distance jusqu'à la prochain station`
In FR

2022-03-17 12:57 UTC, JRH-1997 commented on src/modules/extendedCallList/i18n/nl_NL.root.json
> +            "distance_station": "Distance to next station",
"distance_dispatch": "Afstand tot dichtsbijzijnde meldkamer",
            "distance_station": "Afstand tot dichtsbijzijnde post",

2022-03-17 13:07 UTC, JRH-1997 commented on src/modules/extendedCallList/i18n/nl_NL.root.json
> +            "distance_station": "Distance to next station",
made a typo, changed it.

2022-03-18 11:44 UTC, Suchty112 approved these changes

2022-03-18 16:28 UTC, Ron31 approved these changes

2022-03-18 16:29 UTC, merged