Hotkeys
LSS-Manager/LSSM-V.4 pull request #1819
Opened 2022-10-04 13:18 UTC by Cr4zyc4k3

**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [x] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
- Hotkeys for buildings

2022-10-04 14:09 UTC, kdev approved these changes

2022-10-04 16:03 UTC, jxn-30 requested changes

2022-10-04 16:03 UTC, jxn-30 commented on src/modules/hotkeys/assets/commands/building.ts
> +            (personal as HTMLElement).click();
```suggestion
            const personal = document.querySelector<HTMLAnchorElement>("a[href$='/personals']");
            //No result → Building without personal
            if (personal == null) return;

            personal.click();
```

2022-10-04 16:03 UTC, jxn-30 commented on src/modules/hotkeys/assets/commands/building.ts
> +            (extensionBtn as HTMLElement).click();
```suggestion
            const extensionBtn = document.querySelector<HTMLAnchorElement>("a[href$='/alliance']");
            //No result → Building without enable able extension or extensionen already enabled
            if (
                extensionBtn == null ||
                document.querySelectorAll("a[href*='alliance_costs']").length !=
                    0
            )
                return;

            (extensionBtn as HTMLElement).click();
        },
        disableSharing() {
            const extensionBtn = document.querySelector("a[href$='/alliance']");
            //No result → Building without enable able extension or extensionen already disabled
            if (
                extensionBtn == null ||
                document.querySelectorAll("a[href*='alliance_costs']").length ==
                    0
            )
                return;

            extensionBtn.click();
```

2022-10-04 16:03 UTC, jxn-30 commented on src/modules/hotkeys/assets/commands/building.ts
> +            (extensionBtn as HTMLElement).click();
```suggestion
            const extensionBtn = document.querySelector<HTMLAnchorElement>("a[href$='/alliance']");
            //No result → Building without enable able extension
            if (extensionBtn == null) return;

            extensionBtn.click();
```

2022-10-04 19:08 UTC, Cr4zyc4k3 commented on src/modules/hotkeys/assets/commands/building.ts
> +            (previous as HTMLElement).click();
Would throw a ts-error. `TS2339: Property 'click' does not exist on type 'Element'.`

2022-10-04 19:14 UTC, Cr4zyc4k3 commented on src/modules/hotkeys/assets/commands/building.ts
> +            (next as HTMLElement).click();
Indeed, that's a copy&paste error :see_no_evil: 

Would throw a ts-error. `TS2339: Property 'click' does not exist on type 'Element'.`

2022-10-05 10:34 UTC, jxn-30 approved these changes

2022-10-05 12:49 UTC, merged