🐛 FMS real/show fix totals under dashboard
LSS-Manager/LSSM-V.4 pull request #183
Opened 2020-10-28 16:23 UTC by JRH-1997

I hope this will Fix the issue that the status sum is fms_real on the dashboards. 
Could you look if it's affecting an other module?

2020-10-28 17:22 UTC, KBOE2 approved these changes

2020-10-28 17:42 UTC, Piet2001 approved these changes

2020-10-29 00:53 UTC, JRH-1997 commented
Add buildingHover fix, buildingType '6' of cellbuilding was hardcoded.

2020-10-29 01:18 UTC, KBOE2 requested changes

2020-10-29 01:18 UTC, KBOE2 commented on src/modules/buildingHover/main.ts
> +                )
This does work but I would prefer using newer Code with .includes function:
```suggestion
if(Object.values(LSSM.$t('cellBuildings')).includes(building.building_type))
```

2020-10-29 06:30 UTC, JRH-1997 commented
I used the same code that was used for other buildings in that file. I would also prefer this code.

2020-10-29 06:52 UTC, KBOE2 commented
Oh, looks like I haven't used include myself 😅
If you want to, you can also change the others 🙃

2020-10-29 06:52 UTC, KBOE2 approved these changes

2020-10-29 06:57 UTC, JRH-1997 commented
I will have a look that when I'm at my pc again.

2020-10-29 08:55 UTC, KBOE2 approved these changes

2020-10-29 09:03 UTC, Suchty112 approved these changes

2020-10-29 09:04 UTC, merged