🚒🌲🔥🧑‍🚒✈️ [WIP] US-CP Wildfire Update
LSS-Manager/LSSM-V.4 pull request #2022
Opened 2022-12-16 21:50 UTC by Gooochy

**What kind of update does this PR provide?** *Please check*

- [x] new translations / updated translations / translation fixes
- [x] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
*use the xx_XX notation for exact language!*
* en_US
* ...

**What is included in your update?**
* NEW CP content

**Additional notes**
Please add any further notes here!
Heavy WIP

2022-12-16 22:21 UTC, jxn-30 requested changes

2022-12-16 22:21 UTC, jxn-30 commented on src/modules/extendedCallWindow/i18n/en_US.json
> +        [{ "texts": ["Required Smoke Jumpers (in Smoke Jumper Planes)"],  "vehicles":[76] }],
```suggestion
        "staff": [{ "texts": ["SWAT Personnel"], "vehicles": [16, 26] }, { "texts": ["Required Smoke Jumpers (in Smoke Jumper Planes)"],  "vehicles":[76] }],
```

2022-12-16 22:24 UTC, jxn-30 requested changes

2022-12-16 22:24 UTC, jxn-30 commented on src/modules/extendedCallWindow/i18n/en_US.json
> +                "texts":["Wildland Lead Plane", "Wildland Lead Planes", "vehicles": [75]
```suggestion
                {"texts":["Wildland Lead Plane", "Wildland Lead Planes", "vehicles": [75]}
```

2022-12-16 22:35 UTC, Gooochy commented
@jxn-30 Thank you so much for your help, this was a big challenge for me and your support is greatly appricated!

2022-12-16 22:36 UTC, jxn-30 requested changes

2022-12-16 22:36 UTC, jxn-30 commented on src/modules/missionHelper/i18n/en_US.json
> +        "brush_air_command": "Wildland Air Command Extension" | "Wildland Air Command Extensions",
```suggestion
        "brush_air_command": "Wildland Air Command Extension",
```

2022-12-16 23:12 UTC, Suchty112 requested changes

2022-12-16 23:12 UTC, Suchty112 commented on src/i18n/en_US.ts
> +        Wtank: 1000,
wtank not Wtank

2022-12-16 23:14 UTC, Suchty112 commented
what about the extensions in the buildings? ^^

2022-12-16 23:14 UTC, Gooochy commented on src/i18n/en_US.ts
> +        Wtank: 1000,
Is fixed

2022-12-16 23:47 UTC, Suchty112 commented
@LSS-Manager deploy

2022-12-17 00:08 UTC, Suchty112 commented
@LSS-Manager deploy

2022-12-17 01:05 UTC, jxn-30 commented
@LSS-Manager deploy

2022-12-17 01:17 UTC, jxn-30 commented
@LSS-Manager deploy

2022-12-17 06:10 UTC, Suchty112 approved these changes
LGTM

2022-12-17 09:22 UTC, jxn-30 approved these changes

2022-12-17 09:22 UTC, merged