🌐 Updated fi_FI translations
LSS-Manager/LSSM-V.4 pull request #2056
Opened 2023-01-07 20:39 UTC by Aapeli1304

**What kind of update does this PR provide?** *Please check*

- [x] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
* fi_FI

**Additional notes**
 Added most police and water rescue update translations

2023-01-07 20:43 UTC, Cr4zyc4k3 requested changes

2023-01-07 20:43 UTC, Cr4zyc4k3 commented on src/modules/buildingListFilter/i18n/fi_FI.root.json
> +        { "ids": [2, 4, 5, 20,], "name": "Ensihoito" },
Last comma needs to be removed

2023-01-08 11:59 UTC, jxn-30 approved these changes

2023-01-08 12:10 UTC, Cr4zyc4k3 approved these changes

2023-01-08 12:10 UTC, merged