✨ [emv] Add support for arrHighlight BMA excluding
LSS-Manager/LSSM-V.4 pull request #2231
Opened 2023-03-26 15:00 UTC by Cr4zyc4k3

**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [x] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* arrHighlight should work even on fire alarm system missions or expanded missions

**Additional notes**
Please add any further notes here!

2023-03-27 08:43 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 08:56 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 09:32 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 09:45 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 09:59 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 10:34 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 10:44 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-27 10:53 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-29 13:02 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-03-30 09:16 UTC, jxn-30 requested changes

2023-03-30 09:16 UTC, jxn-30 commented on src/modules/extendedCallWindow/assets/arrMatchHighlight.ts
> +    console.log(wordsPreParsing);
please remove the `console.log`-Statement (see ESLint Warnings) :)

2023-03-30 11:47 UTC, merged