🔀[mH] Don't show at Krankentransporte
LSS-Manager/LSSM-V.4 pull request #2342
Opened 2023-05-11 16:16 UTC by Cr4zyc4k3

**What kind of update does this PR provide?** *Please check*

- [ ] new translations / updated translations / translation fixes
- [x] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**What is included in your update?**
* #25 
> hide for Krankentransporte

**Additional notes**
/

2023-05-11 16:23 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-05-11 16:37 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-05-11 17:23 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-05-11 17:36 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-05-11 17:59 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-05-11 18:20 UTC, Cr4zyc4k3 commented
@LSS-Manager deploy

2023-05-11 18:43 UTC, jxn-30 requested changes

2023-05-11 18:43 UTC, jxn-30 commented on src/modules/missionHelper/i18n/de_DE.json
> +    "ignore_mission_IDs": [143,613],
we could use the root `transfer_missions` translation instead. That would reduce redundant data.

2023-05-11 18:43 UTC, jxn-30 commented on src/modules/missionHelper/i18n/cs_CZ.root.json
> +            "title": "Hide on ambulance missions"
I would suggest/prefer "patient transfer missions". (Same for other EN translations)

2023-05-11 18:43 UTC, jxn-30 commented on src/modules/missionHelper/i18n/es_ES.root.json
> +        },
can we have at least EN translation on non-DE countries?

2023-05-12 14:21 UTC, jxn-30 commented
@LSS-Manager deploy

2023-05-12 14:37 UTC, jxn-30 requested changes

2023-05-12 14:37 UTC, jxn-30 commented on src/modules/missionHelper/main.ts
> +    });
this does not work as `return` onyl exits the promise but not the modules function.

I would suggest the following version (untested):
```suggestion
    const doNotLoad = await getSetting('hide_on_Krankentransport').then(hideBool => {
        const missionID = parseInt(LSSM.$utils.getMissionTypeInMissionWindow());

        return
            Object.values(LSSM.$t('transfer_missions')).includes(missionID) &&
            hideBool;
    });
    if (doNotLoad) return;
```

2023-05-12 18:09 UTC, jxn-30 commented
@LSS-Manager deploy

2023-05-13 00:18 UTC, jxn-30 approved these changes

2023-05-13 00:35 UTC, merged