[sv_SE] add/update translations for missionHelper
LSS-Manager/LSSM-V.4 pull request #2625
Opened 2023-10-01 21:28 UTC by lama77se

Added vehicle caption

**What kind of update does this PR provide?** *Please check*

- [x] new translations / updated translations / translation fixes
- [ ] a new feature
- [ ] a new module
- [ ] a bugfix for an existing feature / module
- [ ] improvement of style or user experience
- [ ] other: *Please fill out*

**Which language(s) did you add/update translations for?**
* sv_SE

**What is included in your update?**
* new SE translation for mission helper

2023-10-01 21:30 UTC, Cr4zyc4k3 approved these changes

2023-10-02 04:03 UTC, jxn-30 requested changes
please also add the changes of #2626 to this branch/pr so that we do have a cleaner history :)

2023-10-02 05:28 UTC, Cr4zyc4k3 commented
> please also add the changes of #2626 to this branch/pr so that we do have a cleaner history :)

In case if this raises a question or you need a some help to do this feel free to ask 😄

2023-10-02 15:52 UTC, jxn-30 approved these changes

2023-10-02 20:18 UTC, merged