🔀🔖 4.7.10
LSS-Manager/LSSM-V.4 pull request #2723
Opened 2023-11-14 14:20 UTC by jxn-30

**Releasenotes**

* 🐛 [redesign] fix tasks and events page
* ⚡ improve performance when many radioMessages come in at once
* ✨ [hotkeys] `building.goto.edit` and `building.goto.move`
* ✨ implement large buildings on all countries
* 🇩🇪 Drohnen-Update
* 🇵🇹 new portugese translations

---
**Releasenotes for translation**
```md
* 🐛 [$m('redesign')] fix tasks and events page
* ⚡ improve performance when many radioMessages come in at once
* ✨ [$m('hotkeys')] `building.goto.edit` and `building.goto.move`
* ✨ implement large buildings on all countries
* 🇩🇪 Drohnen-Update
* 🇵🇹 new portugese translations
```

2023-11-14 14:33 UTC, Cr4zyc4k3 requested changes

2023-11-14 14:33 UTC, Cr4zyc4k3 commented on src/i18n/de_DE/vehicles.ts
> +                        all: true,
Thought only 4 people with training are needed per **drone******

2023-11-14 14:33 UTC, Cr4zyc4k3 commented on src/modules/extendedCallWindow/i18n/fi_FI.json
> +        "removeBeforeParsing": [" (PALOHÄLYTYSJÄRJESTELMÄ)", " [LIITTOUMA]"]
This doesn't seem correct. There is no reason why there should be space at the start.

2023-11-14 18:23 UTC, Suchty112 approved these changes

2023-11-16 10:38 UTC, Cr4zyc4k3 approved these changes

2023-11-16 10:56 UTC, merged